logging:
  config: classpath:logback.xml
# XXJOB参数配置
xxl:
  job:
    accessToken:
    admin:
      addresses: http://192.168.188.135:8093/xxl-job-admin
    executor:
      appname: stock-job-executor
      address:
      ip:
      port: 7979
      logpath: .\logs
      logretentiondays: 30